name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for testing Lambda
        run: npm install

      - name: Run Tests
        run: npm test


      - name: Package report Lambda Function
        run: |
          zip -r report_function.zip . \
          -x "node_modules/*" \
          -x "test/*" \
          -x ".git/*" \
          -x ".github/*" \
          -x "*.log" \
          -x "*.md" \
          -x "package-lock.json"\
          

      - name: List zip contents
        run: |
          unzip -l report_function.zip | sort -n -r | head -n 20
          echo "Total zip size:"
          du -h report_function.zip  

      - name: Deploy to Production Lambda
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws lambda update-function-code \
            --function-name reportlambda \
            --zip-file fileb://report_function.zip \
            --region eu-north-1 \
            --publish

      - name: Wait for Lambda update to complete
        run: sleep 10

      # - name: Update Lambda Function Configuration
      #   if: success()
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws lambda update-function-configuration \
      #       --function-name reportlambda \
      #       --layers ${{ secrets.LAMBDA_LAYER_ARN }}  \
      #       --region eu-north-1
